### ISSUE TITLE
What conferences are folks attending in 2018?

### ISSUE THREAD

**Issue by feross** [feross/confs#3]
Hey friends!

What conferences or meetups are you going to in 2018? I want to hang out with you all, so let's share where we're planning to be :)

I'm going to:

[JavaScript fwdays](https://frameworksdays.com/en/event/js-fwdays-2018) | Mar 18 | Kyiv, Ukraine
[WeAreDevelopers](https://www.wearedevelopers.com) | May 16 - 18 | Vienna
[JSConf Colombia](https://jsconf.co/) | Oct 5 - 6 | Medellín, Colombia

I think these ones would be cool to go to, but I have no solid plans yet:

[DEFCON 26](https://www.defcon.org) | Aug 9 - 12 | Las Vegas
[NodeBoat](http://nodebo.at) | Late September | Copenhagen
[NodeConf EU](http://www.nodeconf.eu) | October | Kilkenny, Ireland
[NodeFest Tokyo](http://nodefest.jp) | Late November | Tokyo
[CCC](http://events.ccc.de) | Late December | Leipzig, Germany
[ArcticJS](http://arcticjs.club) | TBD | Longyearbyen – gotta plan this one first!

Thoughts??

@watson @mcollina @mafintosh @mikeal @yoshuawuyts @flet @diegorbaquero @bcomnes @diasdavid @juliangruber @substack @dominictarr @noffle @dcposch @lrlna @whyrusleeping

**Comment by mikeal** [comment]
JSConf US ;)

**Comment by mcollina** [comment]
When is that happening??? 😱 I would need to go!

**Comment by lrlna** [comment]
I am for certain going to JSConf AU. Outside of your list these are the ones also on my radar tho WebRebels, ScotlandJS, HolyJS SPB, NordicJS, JS Days IT. 

And yea definitely going to NodeFest Tokyo regardless of whether I speak or not!! Such a good conf o/

**Comment by DiegoRBaquero** [comment]
Def going to JSConf Colombia this year, will go to others if I find sponsorship of have enough money.

**Comment by yoshuawuyts** [comment]
Thinking of applying to WebRebels; deadline is end of the week :tada: 
Also yeah: Tokyo every time! :sparkles:

**Comment by dominictarr** [comment]
I'm not planning on any javascript conferences but will be in the bay area for https://www.frontiersf.com/ next month!

**Comment by mikeal** [comment]
@mcollina https://2018.jsconf.us/ :P

**Comment by mafintosh** [comment]
@mikeal uhhhhh, need to submit to that

**Comment by bcomnes** [comment]
Attending https://peer-to-peer-web.com/los-angeles/2018-04-28
